application:

  actions: actions

  web: web-src

  runtimeManifest:

    packages:

      hl-capstone:

        license: Apache-2.0

        actions:

          generic:
            function: actions/generic/index.js
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: true
              final: true

          action1-inf86701:
            function: actions/action1-inf86701/index.js
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
              apiKey: $SERVICE_API_KEY
            annotations:
              require-adobe-auth: true
              final: true

          signup:
            function: actions/signup/index.js
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              include-ims-credentials: true
              final: true
          
          login:
            function: actions/login/index.js
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              include-ims-credentials: true
              final: true

          validate-token:
            function: actions/validate-token/index.js
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              include-ims-credentials: true
              final: true
          
          ingest-products:
            function: actions/ingest-products/index.js
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              include-ims-credentials: true
              final: true
            
          get-products:
            function: actions/get-products/index.js
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              include-ims-credentials: true
              final: true

          get-product-details:
            function: actions/get-product-details/index.js
            web: 'yes'
            runtime: nodejs:22
            inputs:
              LOG_LEVEL: debug
            annotations:
              require-adobe-auth: false
              include-ims-credentials: true
              final: true

    database:
      auto-provision: false
      region: apac